<?php
/**
 * @author Eric Huffman <eric.huffman@gatech.edu>
 *
 * A simple module that makes filter tips collapsible
 *
 */



/**
 * Override filter tips output.
 *
 * @param $variables
 *  An associative array containing:
    tips: An array containing descriptions and a CSS ID in the form of 'module-name/filter-id' (only used when $long is TRUE) for each filter in one or more text formats. Example:
    long: (optional) Whether the passed-in filter tips contain extended explanations, i.e. intended to be output on the path 'filter/tips' (TRUE), or are in a short format, i.e. suitable to be displayed below a form element. Defaults to FALSE.
 * @see
 *  https://api.drupal.org/api/drupal/modules!filter!filter.pages.inc/function/theme_filter_tips/7
 *
 */
function collapsible_filter_tips_theme_registry_alter(&$theme_registry) {
  
  $theme_registry['filter_tips']['theme path'] = drupal_get_path('module', 'collapsible_filter_tips');
  $theme_registry['filter_tips']['function'] = 'collapsible_filter_tips_filter_tips';

}

function collapsible_filter_tips_filter_tips($variables) {
  
  $tips = $variables['tips'];
  $long = $variables['long'];
  $output = '';

  $multiple = count($tips) > 1;
  if ($multiple) {
    $output = '<h2 class="">' . t('Text Formats') . '</h2>';
  }

  if (count($tips)) {
    if ($multiple) {
      $output .= '<div class="compose-tips">';
    }
    foreach ($tips as $name => $tiplist) {
      if ($multiple) {
        $output .= '<div class="filter-type filter-' . drupal_html_class($name) . '">';
        $output .= '<h3>' . check_plain($name) . '</h3>';
      }

      if (count($tiplist) > 0) {
        $output .= '<div class="collapsible-filter-tips-wrapper"><a class="collapsible-filter-tips-wrapper-trigger">' . t('Text Formatting Guidelines') . '</a>';
        $output .= '<ul class="tips collapsed">';
        foreach ($tiplist as $tip) {
          $output .= '<li' . ($long ? ' id="filter-' . str_replace("/", "-", $tip['id']) . '">' : '>') . $tip['tip'] . '</li>';
        }
        $output .= '</ul></div>';
      }

      if ($multiple) {
        $output .= '</div>';
      }
    }
    if ($multiple) {
      $output .= '</div>';
    }
  }

  return $output;

}
